- name: Use metrics system role to configure PCP metrics recording
  hosts: servers
  roles:
    - redhat.rhel_system_roles.metrics
    - redhat.rhel_system_roles.firewall
  become: true

- name: Use metrics system role to configure Grafana
  hosts: metrics_monitor
  roles:
    - redhat.rhel_system_roles.metrics
    - redhat.rhel_system_roles.firewall
  become: true
